# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:31
from __future__ import unicode_literals

import core.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(default=core.models.generate_slug, unique=True)),
                ('type', models.CharField(choices=[(b'Us', b'Usuario'), (b'Ad', b'Administrador'), (b'Gd', b'Guardia')], default=b'Us', max_length=2)),
            ],
            options={
                'db_table': 'Perfil',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=core.models.generate_slug, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('aprobado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Universidad',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='fk_universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universidad', to='core.Universidad'),
        ),
    ]
